USE [master]
GO

/****** Object:  Database [AuctionsSistem]    Script Date: 14/10/2019 20:31:06 ******/
CREATE DATABASE [AuctionsSystem]

 GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AuctionsSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AuctionsSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AuctionsSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AuctionsSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AuctionsSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AuctionsSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [AuctionsSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AuctionsSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AuctionsSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AuctionsSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AuctionsSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AuctionsSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AuctionsSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AuctionsSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AuctionsSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AuctionsSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AuctionsSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AuctionsSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AuctionsSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AuctionsSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AuctionsSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AuctionsSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AuctionsSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AuctionsSystem] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AuctionsSystem] SET  MULTI_USER 
GO

ALTER DATABASE [AuctionsSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AuctionsSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AuctionsSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AuctionsSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AuctionsSystem] SET  READ_WRITE 
GO


